### ISSUE TITLE
Add CF End-User/operators handlers errors in case of chain cascading faults

### ISSUE THREAD

**Issue by f-guichard** [orange-cloudfoundry/sec-group-broker-filter#24]
Hello,

   while trying to extend the sec-group-broker with 3 upstream chained services (cloudstack vpc-router Static NAT + cloudstack vpc-router Port Forwarding + cloudstack vpc-router ACL rules), i end up with an error in the chain service related to cloudstack api controller error (BAD_CREDENTIALS) and no protection for the end-user.

It can also be difficult, even if you're a cloudstack admin/operator, to precisely understand what's going on and where when debbuging the end to end chain.

Same "trouble" than errors handling with bosh cloudstack cpi, see improvements (with netflix hystrix in that case) : 

https://github.com/cloudfoundry-community/bosh-cloudstack-cpi-release/issues/33
https://github.com/cloudfoundry-community/bosh-cloudstack-cpi-release/issues/40

This is not critic for the time being.

**Comment by gberche-orange** [comment]
@f-guichard sorry for late reply on this issue.

Can you please clarify how the cloudstack NAT/port forwarding/ACL rules are related to sec-group-broker filter ? Are you referring to a chain of service brokers ? 

Is this issue rather related to cloudfoundry-community/bosh-cloudstack-cpi-release ?

/CC @poblin-orange 

I'm closing for now, please reopen if this issue makes sense in the context of sec-group-broker filter and please provide a procedure to reproduce it and copy of the errors observed.
