### ISSUE TITLE
Default service plan "free" field defaults to false

### ISSUE THREAD

**Issue by fdehay** [orange-cloudfoundry/sec-group-broker-filter#28]
When a service plan does not set the fields "free" to true, the sec-filter sets it at false.
The doc says default is true : https://docs.cloudfoundry.org/services/api.html

**Comment by s-bortolussi** [comment]
[spring-cloud-cloudfoundry-service-broker](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/issues/25) framework seems to bring this behavior.

**Comment by fdehay** [comment]
so are you going to follow the issue upstream?

**Comment by gberche-orange** [comment]
@fdehay see merged contrib https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/pull/26

**Comment by gberche-orange** [comment]
Closing, upgrades to broker framework managed into #31
